### ISSUE TITLE
Understanding lock lifetime

### ISSUE THREAD

**Issue by lbrito1** [mlanett/redis-lock#25]
I'm not sure I have the correct understanding of what the lock lifetime is supposed to mean.

I expected the `life` argument to specify the maximum amount of seconds any block can hold the lock. If the block exceeds the lifetime, I expect the lock to be released and the block to halt. If the lock is released _but_ the block is able to continue, to my understanding, we defeat the purpose of having a lock in the first place, since other blocks might be in the same critical zone.

Consider the following sscce:

```
require 'redis'
require 'redis-lock'

redis = ::Redis.connect
redis.lock("test", life: 0.1) do
  puts 'Going to sleep'
  sleep 1
  puts 'Dark side of the moon'
end
```

I expect 'Dark side of the moon' never to be printed, because the block exceeded the lock lifetime. This is not, however, what happens:

```
$ ruby sscce.rb 
DEBUG>>>do_lock() success # (logger replaced with puts)
Going to sleep
Dark side of the moon
```

Please let me know if I am misunderstanding the purpose or meaning of lock lifetime.

**Comment by inossidabile** [comment]
This is a totally wrong understanding. On timeout the flag in Redis is released and that allows another process to start with it. But it doesn't abort block and for the god sake it shouldn't :). Just make sure you are extending the actual lock flag properly to keep it alive _at least_ during the block run.

This timeout in general is only serving the purpose of not having a persistent deadlock ever. If your process crashes - it's only up to this timeout to define when lock is over.

**Comment by lbrito1** [comment]
Great info @inossidabile ! Thanks
